
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import SimpleNav from "@/components/SimpleNav";
import Sidebar from "@/components/Sidebar";
import { DockDemo, FloatingDockDemo } from "@/components/Floatdoc";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <DockDemo />
      </body>
    </html>
  );
}
